# Generated by Django 5.1.6 on 2025-02-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_customer_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='sellerapp.product')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='sellerapp.product')),
            ],
        ),
    ]
