# Generated by Django 5.1.6 on 2025-02-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_category_alter_product_category_delete_producttree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
