name: App Deployment

on:
  push:
    branches: [ "master" ]
jobs:
  git-checkout:
    runs-on: self-hosted
    steps:
    # Ensure the directory is clean before cloning repo
    - name: Clean the workspace
      run: |
          find . -mindepth 1 -delete
    
    # Clone the repo
    - name: Clone repository
      run: |
         git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} .
    
    # Create an Image
    - name: Build Docker image
      run: |
        ls -l
        cp requirements.txt eseller && cd eseller
        docker build -t seller-app-v1 .
