name: App Deployment

on:
  push:
    branches: [ "master" ]
jobs:
  git-checkout:
    runs-on: self-hosted
    steps:
    # Ensure the directory is clean before cloning repo
    - name: Clean the workspace
      run: |
          find . -mindepth 1 -delete
    
    # Clone the repo
    - name: Clone repository
      run: |
         git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} .
    
    # Create an Image
    - name: Build Docker image
      run: |
        docker build -t seller-app-v1 -f eseller/Dockerfile .
        
    # Launch a Docker container from the created image
    - name: Launch Container
      run: | 
        # Stop and remove current running container and create new container from 
        # incoming pushed code changes
        docker stop sellerapp
        docker rm sellerapp
        docker run -it -dp 8050:8050 --name sellerapp seller-app-v1
        docker system prune -a -f
        docker image prune -a -f
